### ISSUE TITLE
cmake version

### ISSUE THREAD

**Issue by pierrepeterlongo** [algbio/SBWT#5]
Hi !

The CMake minimal version should be at least 3.13 to accept `target_link_options`

See https://cmake.org/cmake/help/git-stage/command/target_link_options.html

Best, 
Pierre

**Comment by jnalanko** [comment]
Thanks. Fixed in commit [9711157](https://github.com/algbio/SBWT/commit/97111572ae04a9b376be2ab757d3845194d460b4).
